# Warning: do not edit this file.  It is automatically generated from git://server/puppet-site.tmpl
import "roles.pp"

node 'puppetmaster1.peoplemerge.com' {
	include standard
}
node 'refactor5test1.peoplemerge.com' {
	include web
}
node 'refactor5test2.peoplemerge.com' {
	include web
}
node 'refactor5test3.peoplemerge.com' {
	include db
}
