# Warning: do not edit this file.  It is automatically generated from git://server/puppet-hosts.tmpl
class hosts {
        host {'ino.peoplemerge.com':
                ensure => present,
                host_aliases => ['ino'],
                ip => '192.168.10.105'
        }
        host {'puppetmaster1.peoplemerge.com':
                ensure => present,
                host_aliases => ['puppetmaster1'],
                ip => '192.168.10.137'
        }
        host {'refactor5test1.peoplemerge.com':
                ensure => present,
                host_aliases => ['refactor5test1'],
                ip => '192.168.10.146'
        }
        host {'refactor5test2.peoplemerge.com':
                ensure => present,
                host_aliases => ['refactor5test2'],
                ip => '192.168.10.147'
        }
        host {'refactor5test3.peoplemerge.com':
                ensure => present,
                host_aliases => ['refactor5test3'],
                ip => '192.168.10.148'
        }
}